In [6]:
import gtsam

In [2]:
#### FILTER OBJECT
class GraphTracker():
    def __init__(self):
        
        # Member variables
        self.init = False
        self.detections = []
        self.tracks = []
        self.graph = gtsam.NonlinearFactorGraph()
        self.trk_delete_thresh = 0.25
        self.trk_delete_age = 10
        self.trk_create_thresh = 0.75

    # Member functions
    def handle_detections(self,det_array_msg):
        self.detections = det_array_msg.boxes
        
        # TODO - Compute detection-track correspondences
        
        # TODO - Assign detections to track variables
        
        # TODO - create tracks as needed
        
        # Delete tracks as needed
        self.delete_tracks()
        
    def delete_tracks(self):
        self.tracks = [track for track in self.tracks if track.prob < self.trk_delete_thresh]
        self.tracks = [track for track in self.tracks if track.age > self.trk_delete_age]
        
    # birth
    # compute assignment
    # add factors
    # optimize

In [5]:
#### DETECTION OBJECT
class Detection():
    def __init__(self, det_msg):
        self.px = det_msg.pose.position.x
        self.py = det_msg.pose.position.y
        self.pz = det_msg.pose.position.z
        self.age = 0
        self.prob = det_msg.value
        self.class = det_msg.label
        # Can be empty/null/contain partial info
        # class conf % - float
        # ??? BB dimensions

#### TRACK OBJECT
class Track():
    def __init__(self, det):
        self.px = det.px
        self.py = det.py
        self.pz = det.pz
        self.vx = 0
        self.vy = 0
        self.vz = 0
        self.prob = 
        self.age = det.age
        # heading in world frame
        # self.class = categorical distribution!
        # ??? class conf %

In [ ]:
#### HELPER FUNCTIONS
# Similarity metric (detection, track)

# Form similarity matrix (detections, tracks) -> return similarity matrix
# - call similarity metric

# Hungarian/Munkres algo (similarity matrix) -> return assignments (T_match, D_match, T_unmatch (missed/occ), D_unmatch (false, new obj, extra detection)


In [5]:
import numpy as np
from scipy.optimize import linear_sum_assignment

# Create a cost matrix
cost_matrix = np.array([
    [4, 1, 3],
    [2, 0, 5],
    [3, 2, 2],
    [0, 0, 0]
])

# Solve the assignment problem
row_indices, col_indices = linear_sum_assignment(cost_matrix)

# Extract the optimal assignment
assignment = [(row, col) for row, col in zip(row_indices, col_indices)]

print("Optimal Assignment:")
for row, col in assignment:
    print(f"Resource {row} assigned to Task {col}")


Optimal Assignment:
Resource 1 assigned to Task 1
Resource 2 assigned to Task 2
Resource 3 assigned to Task 0


In [18]:
def cost(det,track):
    return np.abs(det-track)

def compute_cost_matrix(detects, tracks):
    cost_matrix = np.zeros((len(detects),len(tracks)))
    for ii,det in enumerate(detects):
        for jj,trk in enumerate(tracks):
            cost_matrix[ii,jj] = cost(det,trk)
    return cost_matrix  

tracks = [1, 2, 3]
det = [0.9, 3.1, 2.1, 4.4]

cost_matrix = compute_cost_matrix(det,tracks)

# Solve the assignment problem
row_indices, col_indices = linear_sum_assignment(cost_matrix)

# Extract the optimal assignment
assignment = [(row, col) for row, col in zip(row_indices, col_indices)]

In [19]:
print(cost_matrix)

print("Assign this detection")
print(row_indices)
print("To this track")
print(col_indices)
print(assignment)

[[0.1 1.1 2.1]
 [2.1 1.1 0.1]
 [1.1 0.1 0.9]
 [3.4 2.4 1.4]]
Assign this detection
[0 1 2]
To this track
[0 2 1]
[(0, 0), (1, 2), (2, 1)]
